export const ValidationConstants  ={
    ADMIN : {
        FIRSTNAME_MIN_LENGTH: 2,
        FIRSTNAME_MAX_LENGTH: 15,
        LASTNAME_MIN_LENGTH:3,
        LASTNAME_MAX_LENGTH:30,
        EMAIL_MIN_LENGTH:5,
        EMAIL_MAX_LENGTH:100,
        PASSWORD_MIN_LENGTH :8,
        PASSWORD_MAX_LENGTH:50,
        PASSWORD_MUST_CONTAINS_ONE_CHARACTER:true,
        PASSWORD_MUST_CONTAINS_ONE_UPPERCASE:true,
        PASSWORD_MUST_CONTAINS_ONE_LOWERCASE:true,
        PASSWORD_MUST_CONTAINS_ONE_DIGIT:true,
    }
}